language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: SYMFONY_VERSION="~2.7"
        - php: 5.6
          env: SYMFONY_VERSION="~3.0@dev" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN="8e0cd1566d8bcf657043858efb02e60ac953b34ee1ee4f5a19c5a9f4432c2d73" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: 8e0cd1566d8bcf657043858efb02e60ac953b34ee1ee4f5a19c5a9f4432c2d73

after_success:
    - php vendor/bin/coveralls -v
