name: PHPStan

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.2', '7.3', '7.4']
                composer-flags: ['--prefer-stable --prefer-lowest', '']
                symfony: ['~3.4', '~4.4', '~5.0']
        name: PHP ${{ matrix.php }} SF ${{ matrix.symfony }} (${{ matrix.composer-flags }}) on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo, pecl
                  extensions: intl

            - name: Install AST
              run: |
                  sudo pecl channel-update pecl.php.net
                  sudo pecl install ast

            - name: Fix Symfony version
              run: |
                  composer req symfony/flex
                  composer config extra.symfony.require "${{ matrix.symfony }}"

            - name: Install Composer deps
              run: |
                  composer update ${{ matrix.composer-flags }} --no-interaction --no-suggest

            - name: Install Phive
              run: |
                  wget -O phive.phar https://phar.io/releases/phive.phar
                  wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
                  gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
                  gpg --verify phive.phar.asc phive.phar
                  chmod +x phive.phar
                  sudo mv phive.phar /usr/local/bin/phive
                  phive install

            - name: Run PHPStan
              run: |
                  ./tools/phpstan analyse src -c phpstan.neon --level max
              env:
                  SYMFONY_DEPRECATIONS_HELPER: weak_vendors
