name: PHPunit

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.4']
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo
                  extensions: intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest

            - name: Install Phive
              run: |
                  wget -O phive.phar https://phar.io/releases/phive.phar
                  wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
                  gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
                  gpg --verify phive.phar.asc phive.phar
                  chmod +x phive.phar
                  sudo mv phive.phar /usr/local/bin/phive
                  phive install

            - name: Run PHPunit
              run: |
                  ./tools/phpunit --verbose --debug
              env:
                  SYMFONY_DEPRECATIONS_HELPER: weak_vendors
